name: Create Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Sync version first
        run: |
          echo "Syncing version before building..."
          npm run version-sync
          echo "Version sync completed"

      - name: Build plugin
        run: npm run build

      - name: Prepare release folder
        run: |
          mkdir release
          cp custom-fields-block.php release/
          cp package.json release/
          cp README.md release/
          cp INSTALLATION.md release/
          cp -r build release/
          if [ -d languages ]; then cp -r languages release/; fi

      - name: Create ZIP
        run: |
          cd release
          zip -r ../custom-fields-block.zip .

      - name: Delete existing assets
        run: |
          # Get release ID with error handling
          RELEASE_RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.ref_name }}")

          echo "Release response: $RELEASE_RESPONSE"

          RELEASE_ID=$(echo "$RELEASE_RESPONSE" | jq -r '.id // empty')

          if [ -z "$RELEASE_ID" ]; then
            echo "Could not get release ID, skipping asset deletion"
            exit 0
          fi

          echo "Release ID: $RELEASE_ID"

          # Get existing assets with error handling
          ASSETS_RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID/assets")

          echo "Assets response: $ASSETS_RESPONSE"

          # Check if response is valid JSON array
          if echo "$ASSETS_RESPONSE" | jq -e 'type == "array"' > /dev/null 2>&1; then
            ASSETS=$(echo "$ASSETS_RESPONSE" | jq -r '.[] | select(.name == "custom-fields-block.zip") | .id // empty')
            
            # Delete existing assets
            for asset_id in $ASSETS; do
              if [ ! -z "$asset_id" ]; then
                echo "Deleting asset ID: $asset_id"
                curl -X DELETE -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
                  "https://api.github.com/repos/${{ github.repository }}/releases/assets/$asset_id"
              fi
            done
          else
            echo "Invalid assets response, skipping deletion"
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: custom-fields-block.zip
          generate_release_notes: true
          draft: false
          prerelease: false
          body: |
            ## Changelog

            ### Version ${{ github.ref_name }}

            - Verbesserte Debug-Funktionen für Update-System
            - Korrigierte Einstellungsseite mit WordPress Settings API
            - Zentrales Custom Fields Caching-System
            - Dropdown direkt im Block integriert
            - Automatische Cache-Verwaltung

            ### Installation

            1. Deaktiviere das aktuelle Plugin
            2. Lade die ZIP-Datei hoch
            3. Aktiviere das Plugin wieder

            ### Bekannte Probleme

            Falls das Update fehlschlägt:
            1. Gehe zu Einstellungen → Custom Fields Block
            2. Klicke "Update Cache leeren"
            3. Versuche das Update erneut
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
