name: Create Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Verify version sync
        run: |
          echo "Checking if version is properly synced..."
          PLUGIN_VERSION=$(grep "Version:" custom-fields-block.php | head -1 | sed 's/.*Version: //')
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "Plugin version: $PLUGIN_VERSION"
          echo "Package version: $PACKAGE_VERSION"
          if [ "$PLUGIN_VERSION" != "$PACKAGE_VERSION" ]; then
            echo "Versions don't match! Syncing..."
            npm run version-sync
          fi

      - name: Build plugin
        run: npm run build

      - name: Prepare release folder
        run: |
          mkdir release
          cp custom-fields-block.php release/
          cp package.json release/
          cp README.md release/
          cp INSTALLATION.md release/
          cp -r build release/
          if [ -d languages ]; then cp -r languages release/; fi

      - name: Create ZIP
        run: |
          cd release
          zip -r ../custom-fields-block.zip .

      - name: Delete existing assets
        run: |
          # Get release ID
          RELEASE_ID=$(curl -s -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.ref_name }}" | \
            jq -r '.id')

          # Get existing assets
          ASSETS=$(curl -s -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID/assets" | \
            jq -r '.[] | select(.name == "custom-fields-block.zip") | .id')

          # Delete existing assets
          for asset_id in $ASSETS; do
            curl -X DELETE -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/releases/assets/$asset_id"
          done

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: custom-fields-block.zip
          generate_release_notes: true
          draft: false
          prerelease: false
          body: |
            ## Changelog

            ### Version ${{ github.ref_name }}

            - Verbesserte Debug-Funktionen für Update-System
            - Korrigierte Einstellungsseite mit WordPress Settings API
            - Zentrales Custom Fields Caching-System
            - Dropdown direkt im Block integriert
            - Automatische Cache-Verwaltung

            ### Installation

            1. Deaktiviere das aktuelle Plugin
            2. Lade die ZIP-Datei hoch
            3. Aktiviere das Plugin wieder

            ### Bekannte Probleme

            Falls das Update fehlschlägt:
            1. Gehe zu Einstellungen → Custom Fields Block
            2. Klicke "Update Cache leeren"
            3. Versuche das Update erneut
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
