name: Create Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build plugin
        run: npm run build

      - name: Prepare release folder
        run: |
          mkdir release
          cp custom-fields-block.php release/
          cp README.md release/
          cp INSTALLATION.md release/
          cp -r build release/
          if [ -d languages ]; then cp -r languages release/; fi

      - name: Create ZIP
        run: |
          cd release
          zip -r ../custom-fields-block.zip .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: custom-fields-block.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
